baseurl                 = "http://paralune.com/"
languageCode            = "en-us"
title                   = "Paralune"
theme                   = "hugo-phlat-theme"
description             = "Paralune is a game studio making games about feelings."

[permalinks]
    post                = "/:year/:month/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"

# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"

[[menu.header]]
    name                = "Presskit"
    weight              = 2
    url                 = "http://press.mythicoceangame.com"

[[menu.header]]
    name                = "About"
    weight              = 3
    url                 = "/about/"

[[menu.header]]
    name                = "Jobs"
    weight              = 4
    url                 = "/jobs/"

[[menu.header]]
    name                = "Mailing List"
    weight              = 5
    url                 = "http://eepurl.com/dnNdaf"

[[menu.header]]
    name                = "Mythic Ocean"
    weight              = 6
    url                 = "/mythic-ocean/"

# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
# [[menu.footer]]
#    name                = "Privacy Policy"
#    weight              = 1
#    url                 = "/privacy-policy/"

[params]
    keywords            = ["paralune", "indie games", "game studio", "mythic ocean", "underwater", "exploration"]
    description         = "Paralune is a 3-person game studio based in Austin, TX. We make narrative-focused games that allow our players to be storytellers, too."
    copyright           = "Copyright 2019 Paralune, LLC"
    twitter             = "@ParaluneGames"
    meta_image          = "http://paralune.com/images/paralune-meta-card.jpg"
    google_analytics    = ""
    google_adsense      = ""
    disqus              = "paralune"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = "/images/favicon.ico"
    fontbody            = "Droid+Serif"
    fontheading         = "Copse"
    paginate            = 5

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://twitter.com/ParaluneGames"
    googleplus          = ""
    linkedin            = ""
    youtube             = "https://www.youtube.com/channel/UCVkwnM-fd8gv5Fsx7FuDA7Q"
    paypal              = ""
    instagram           = "https://www.instagram.com/mythicoceangame/"
    reddit              = ""
    email               = "mailto:contact@paralune.com"
    pinterest           = ""
    wordpress           = ""
